/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: El Alquimista𓁞 (https://sketchfab.com/ElCanciller)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/kirby-180c0f5600e44517a431c9b488a548e1
title: Kirby
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-0.84, -0.28, -0.3]} rotation={[2.52, 0.27, 0.31]} scale={[0.42, 0.39, 0.39]}>
          <mesh geometry={nodes['black-material'].geometry} material={materials.black} />
          <mesh geometry={nodes['black-material_1'].geometry} material={materials.black} />
          <mesh geometry={nodes['black-material_2'].geometry} material={materials.black} />
          <mesh geometry={nodes['black-material_3'].geometry} material={materials.black} />
        </group>
        <group position={[-0.84, -0.28, -0.3]} rotation={[2.52, 0.27, 0.31]} scale={[0.42, 0.39, 0.39]}>
          <mesh geometry={nodes['manos-material'].geometry} material={materials.manos} />
          <mesh geometry={nodes['Material-material'].geometry} material={materials.Material} />
          <mesh geometry={nodes['shoes-material'].geometry} material={materials.shoes} />
          <mesh geometry={nodes['shoes-material_1'].geometry} material={materials.shoes} />
        </group>
        <group position={[4.08, 1.01, 5.9]} rotation={[-0.27, 0.6, 1.93]} />
        <group position={[7.48, -6.51, 5.34]} rotation={[0.94, 0.71, 0.44]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
